name: GraalVM CE CI

on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
    paths-ignore:
      - '**.yml'
      - '**.md'
      - '**/gradle-wrapper.jar'
      - '**/gradle-wrapper.properties'
      - '**/gradlew'
      - '**/gradlew.bat'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-

      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 22.3.0.java17

      - name: Install Native Image
        run: gu install native-image

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push Docker Image
        env:
          DOCKER_REPOSITORY_PATH: ${{ vars.DOCKER_USERNAME }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE=`echo "${DOCKER_REPOSITORY_PATH}/the-first-descendant-open-community-api" | sed -e 's#//#/#' -e 's#^/##'`
          ./gradlew check dockerPushNative --no-daemon