name: Java CI with Gradle (Groovy)

on:
  workflow_dispatch: { }
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - '**/gradle-wrapper.jar'
      - '**/gradle-wrapper.properties'
      - '**/gradlew'
      - '**/gradlew.bat'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts
        path: |
          **/build/reports